/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controle.ControleLogin;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author fabricioguidine
 */
public class TelaLoginGerencia extends javax.swing.JFrame {
    
    private ControleLogin cl = new ControleLogin();
    
    JFrame telaAnterior;
    /**
     * Creates new form login
     */
    private TelaLoginGerencia() {
        initComponents();
    }
    
    public TelaLoginGerencia(JFrame telaAnterior){
        this();
        this.telaAnterior = telaAnterior;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cancelar = new javax.swing.JLabel();
        labelEntrar = new javax.swing.JLabel();
        Entrar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        labelAjuda = new javax.swing.JLabel();
        botaoAjuda = new javax.swing.JButton();
        campoUsuario = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        separadorSenha = new javax.swing.JSeparator();
        separadorUsuario = new javax.swing.JSeparator();
        labelSenha = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelFundoIcone = new javax.swing.JLabel();
        labelFundoLogin = new javax.swing.JLabel();
        labelFundo2 = new javax.swing.JLabel();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cancelar.setText("Cancelar");
        getContentPane().add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 70, 50));

        labelEntrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEntrar.setText("Entrar");
        getContentPane().add(labelEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 60, 50));

        Entrar.setForeground(new java.awt.Color(255, 153, 153));
        Entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/form.png"))); // NOI18N
        Entrar.setBorder(null);
        Entrar.setBorderPainted(false);
        Entrar.setContentAreaFilled(false);
        Entrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 320, 70));

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/entrar.png"))); // NOI18N
        cancelar.setBorder(null);
        cancelar.setBorderPainted(false);
        cancelar.setContentAreaFilled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 230, -1));

        labelAjuda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAjuda.setText("Ajuda");
        getContentPane().add(labelAjuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        botaoAjuda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/entrar.png"))); // NOI18N
        botaoAjuda.setBorder(null);
        botaoAjuda.setBorderPainted(false);
        botaoAjuda.setContentAreaFilled(false);
        getContentPane().add(botaoAjuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 230, -1));

        campoUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        campoUsuario.setText("Entre com seu usuário...");
        campoUsuario.setBorder(null);
        campoUsuario.setOpaque(false);
        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 250, 30));

        campoSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoSenha.setForeground(new java.awt.Color(153, 153, 153));
        campoSenha.setText("Entre com sua senha...");
        campoSenha.setBorder(null);
        campoSenha.setOpaque(false);
        getContentPane().add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 250, 30));
        getContentPane().add(separadorSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 250, 10));
        getContentPane().add(separadorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 250, 10));

        labelSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(240, 240, 240));
        labelSenha.setText("Senha");
        getContentPane().add(labelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        labelUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(240, 240, 240));
        labelUsuario.setText("Usuário");
        getContentPane().add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        labelFundoIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/avatar.png"))); // NOI18N
        getContentPane().add(labelFundoIcone, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        labelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/login.png"))); // NOI18N
        getContentPane().add(labelFundoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        labelFundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/fundo2.png"))); // NOI18N
        getContentPane().add(labelFundo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/fundo.png"))); // NOI18N
        getContentPane().add(labelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // Botão salvar foi pressionado:
        telaAnterior.setEnabled(true);
        this.dispose();
      
    }//GEN-LAST:event_cancelarActionPerformed

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        // TODO add your handling code here:
        String usuario = this.campoUsuario.getText().trim();
        String senha = this.campoSenha.getText().trim();
        if(cl.VerificaLogin(usuario, senha) == true){
            telaGerencia tg = new telaGerencia(this);
            tg.setVisible(true);
            tg.setSize(800, 600);
            tg.setResizable(false);
            this.setEnabled(false);
       } 
       else{
           JOptionPane.showMessageDialog(null, "Login incorreto!");
       }
    }//GEN-LAST:event_EntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginGerencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cancelar;
    private javax.swing.JButton Entrar;
    private javax.swing.JButton botaoAjuda;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel labelAjuda;
    private javax.swing.JLabel labelEntrar;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelFundo2;
    private javax.swing.JLabel labelFundoIcone;
    private javax.swing.JLabel labelFundoLogin;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JSeparator separadorSenha;
    private javax.swing.JSeparator separadorUsuario;
    // End of variables declaration//GEN-END:variables
}
